import type { Metadata } from "next";
import "./globals.css";
import Header from "./Components/Header/Header";
import SideBar from "./Components/Header/SideBar";

export const metadata: Metadata = {
  title: "Soft Solution Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F6F6F6] w-full min-w-full min-h-screen">
        <Header />
        <div className="flex flex-col md:flex-row justify-between gap-4 w-full">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
